### ISSUE TITLE
Filtering out unknown elements

### ISSUE THREAD

**Issue by naquad** [siriusphp/validation#12]
It would be awesome if Validator would also filter out unknown elements and provide filtered input.

An example should sched some light:

```
$data = [
  'id' => '123',
  'email' => 'asd@gmail.com',
  'text' => 'some text here',
  'submit' => 'Send',
  'some_value_user_posted' => '123',
  // other unknown/unused fields
];

$validator = new \Sirius\Validation\Validator();

$validator->add([
  'id' => 'required|number',
  'email' => 'required|email',
  'text' => 'required'
]);

if(!$validator->validate($data)){
  send_errors($validator->getMessages());
}else{
  $clean_data = $validator->data();
  // and $clean_data contains only id, email and text, nothing else
}

```

**Comment by kenjis** [comment]
Hi, I customized Sirius Validation and added the functionality.
https://github.com/kenjis/secure-validator

**Comment by adrianmiu** [comment]
Looks interesting. The code below is limiting, no?

```php
                    if (preg_match('/(.+)\[(.+)\]\[(.+)\]/i', $valueIdentifier, $matches)) {
                        $name = $matches[1];
                        $key1 = $matches[2];
                        $key2 = $matches[3];
                        $this->validatedData[$name][$key1][$key2] = $value;
                    } else {
                        $this->validatedData[$valueIdentifier] = $value;
                    }
```

Either it will handle something like $_POST['key'] or $_POST['key']['key1']['key2']. Nothing else.

**Comment by kenjis** [comment]
Thank you for your comment.

I'm not sure my code is really right, but the answer is no.

See https://github.com/kenjis/secure-validator/commit/07350267690cb84f5f63ce62f8d5038946351a58
The tests pass.

$_POST['key']
$_POST['key']['key1']
$_POST['key']['key1']['key2']['key3']
are okay.
