### ISSUE TITLE
Integrate Filtration into validation Syntax?

### ISSUE THREAD

**Issue by mscreenie** [siriusphp/validation#18]
Would it be possible to use filtration inside the same rule syntax?

```
$validator->add('title', 'required | maxlength(max=255) | minlength(min=10) | sirius(strip_tags)');
```

Thanks for putting work into this, useful class which I'll be using.

**Comment by adrianmiu** [comment]
I was thinking about it but there are many problems with this approach:
1. it would have 2 responsibilities
2. it might give unexpected results, in the sense that you have to really be careful where you put the filters (before or after validation). required|strip_tags|minlength or strip_tags|required|minlength?
I already have a library for filtration `siriusphp/filtration`
