### ISSUE TITLE
Example on using regex validation 

### ISSUE THREAD

**Issue by mscreenie** [siriusphp/validation#20]
Could you post here or update docs on how to properly use the regex syntax within sirius. 

How would you pass a pattern using match?

**Comment by adrianmiu** [comment]
When using the shorthand notation the format is `filter_name(parameters_list)`. Where `parameters_list` is a URL-query like string (eg: sort_by=name&sort=asc&page=3)

If you look at the Regex rule https://github.com/siriusphp/validation/blob/master/src/Rule/Regex.php you will see the constant `OPTION_RULE = 'pattern'`. Every rule class has its constants to help your IDE and also tell you what options the rule accepts.

```php
$validator->addRule('email', 'regex(rule=/your_regex_goes_here/)');
```

Unlike other validator libraries that take the shorthand notation too far, with Sirius ALL filter parameters must be named and each class has constants that define the names of the parameters that are required by that rule.
