### ISSUE TITLE
MaxLength/MinLength doesn't support multibyte letters

### ISSUE THREAD

**Issue by kenjis** [siriusphp/validation#29]
`$this->success = strlen($value) <= $this->options['max'];`
https://github.com/kenjis/siriusphp-validation/blob/master/src/Rule/MaxLength.php#L24

> strlen() returns the number of bytes rather than the number of characters in a string. 
http://php.net/manual/en/function.strlen.php

Why don't you use `mb_strlen()`?

**Comment by adrianmiu** [comment]
fixed by 4c06b24679f3b77ed6d3a5703fb909c5b9dbdca5
