### ISSUE TITLE
getMessages returns unformatted message

### ISSUE THREAD

**Issue by mscreenie** [siriusphp/validation#32]
Hi when I try to retrieve errors with $validator->getMessages()

I get a unformatted response. I've reverted back to an older version where this does not happen.

I'm referring to this part: {label} is required

            [0] => Sirius\Validation\ErrorMessage Object
                (
                    [template] => {label} is required
                    [variables] => Array
                        (
                            [label] => Name
                            [value] => 
                        )
                )

case:

            $validator->add(array(
                'name:Name' => 'required | maxlength(100)',
                'username:Username' => 'required | maxlength(100)',
            ));

**Comment by adrianmiu** [comment]
The library does not return `strings` as the error messages http://www.sirius.ro/php/sirius/validation/error_message.html

If you want to access the message as string just write (as in the case above)
```php
(string)$messages['name'][0]
```
