### ISSUE TITLE
Regex pattern containing braces parced incorrectly

### ISSUE THREAD

**Issue by velosipedist** [siriusphp/validation#34]
If i add rule

```
regex((\+7)?\d\d\d-\d\d\d\d\d\d\d)
```

then i got Regex rule with just  `(\+7` parsed.

As temporarily workaround i'd preferred to add some rules in list of addMultiple() as Regex instances. But it is also impossible for now :(

**Comment by adrianmiu** [comment]
Unfortunately, the syntactic sugar implementation makes it impossible to use braces.
http://www.sirius.ro/php/sirius/validation/syntactic_sugar.html shows that besides the validator options you can pass the error message in braces. 

A more complex algorithm is needed to make that happen but I am very busy at the moment. I am accepting PRs though :)

**Comment by velosipedist** [comment]
I understood about string definitioins of validators, but why not to support passing of validator instances?

**Comment by adrianmiu** [comment]
I haven't read your comment closely enough to see you asked for validator instances. I haven't done it because I haven't thought about it. The value proposition of such feature is very small IMHO. You don't have to use the syntactic sugar to add multiple rules and use the "verbose way".

```php
$validator->add('postal_code', array(
     array('required'),
     array('length', array(4,10)),
     array('regex', array('/[0-9 ]+/'))
));
```

http://www.sirius.ro/php/sirius/validation/syntactic_sugar.html (point 4.)

**Comment by velosipedist** [comment]
Yeaah, thanks :) It is absolutely enough.

**Comment by velosipedist** [comment]
Just checked your solution, it work, but Rule writes passed pattern to options[0] instead of options['pattern']. And therefore, it will never be passed correctly, because it seeks only options['pattern'].

**Comment by dam2k** [comment]
this one is wrong !
...
>      array('regex', array('/[0-9 ]+/'))
...

Should be like this:
>      array('regex', '/[0-9 ]+/')
