### ISSUE TITLE
Only evaluating the first rule?

### ISSUE THREAD

**Issue by hbarroso** [siriusphp/validation#36]
Hi,

Either I'm missing something completely obvious or might there be bug in the version 2.1.
It seems that, when passing an array to the `add` method, it only adds or evaluates the first rule.

```php

    $validator = new Validator();
    
    $input = ['title' => 'Some title'];
    
    $validator->add(array(
        'title:Title' => 'required',
        'content:Content' => 'required | minlength(5)',
    ));
    
    if ($validator->validate($input)) {
        echo "all good";
    } else {
       var_dump($validator->getMessages();
    }
```

If you run this code, it returns `true` even though the `content` is not included in the `$input` array. But the funny thing is, even if I change the `$input` to:

```
    $input = ['title' => 'Some title', 'content'  => 'foo'];
```

This still returns true, even though content is less than 5 chars.

What am I missing?

thanks,

**Comment by adrianmiu** [comment]
Yes. It is a problem when adding multiple rules using the string definition
Adding multiple rules works if they are passed as array (not strings separated by ` | `):
https://github.com/siriusphp/validation/blob/master/tests/src/ValidatorTest.php#L113

Adding single rules as strings works
https://github.com/siriusphp/validation/blob/master/tests/src/ValidatorTest.php#L159

Will fix as soon as I have some time.

**Comment by mscreenie** [comment]
Any eta on a fix? The example in docs does not seem to work either?

**Comment by adrianmiu** [comment]
@mscreenie I'm extremely busy at the moment but I would approve at a pull-request :)

**Comment by vikkio88** [comment]
Hello, I just opened a PR which fixes this Issue
