### ISSUE TITLE
No message when json_encode($validator->getMessages())

### ISSUE THREAD

**Issue by KazeFlame** [siriusphp/validation#39]
Scenario: I'm developing an API-centric application so every form submission are done in AJAX. The response headers are `application/json` so I need to `json_encode` the data. But that causes the messages in the validator to output nothing.

I have a dirty workaround for this.

```
    /**
     * Format messages and make them string for json output.
     *
     * @param array $messages
     * @return array
     */
    protected function formatMessagesForJsonOutput(array $messages)
    {
        $formatter = function ($value)
        {
            return (string) $value[0];
        };

        return array_map($formatter, $messages);
    }
```

It would be great if the library automatically convert the error messages into string for `json_encode`.

**Comment by adrianmiu** [comment]
I see what you mean but automatically converting the messages to string prevents manipulating them in HTML view (ie: for translating).
