### ISSUE TITLE
"AlphaNumHyphen" did not type control

### ISSUE THREAD

**Issue by enesgur** [siriusphp/validation#40]
Hello, 

When i used "AlphaNumHyphen" validator for an array object, php has gave a notice and it's validation returned true.

```php
$object = ['array' => ['field1', 'field2']];
$validation->add('array', 'required');
$validation->add('array', 'AlphaNumHyphen');
$validation->validate($object);
```

"A PHP Error was encountered

Severity: Notice

Message: Array to string conversion

Filename: Rule/AlphaNumHyphen.php

Line Number: 23"

and return true.

PHP Version: 5.6
Sirius/validation: 2.1.2

**Comment by adrianmiu** [comment]
if you want to validate every element of an array you should use

```php
$validation->add('array[*]', 'required');
$validation->add('array[*]', 'AlphaNumHyphen');
```

**Comment by adrianmiu** [comment]
Check this out: http://www.sirius.ro/php/sirius/validation/
The first example shows how to target deep elements of an array
