### ISSUE TITLE
Empty strings, that are not required, undergo further validation

### ISSUE THREAD

**Issue by sergiobelya** [siriusphp/validation#52]
If I send empty value from form (as empty string), this value will be tested (eg, Integer, GreaterThan), even if it is not required.

See https://github.com/siriusphp/validation/blob/2.2.1/src/ValueValidator.php#L258

**Comment by adrianmiu** [comment]
@sergiobelya Thanks for the pull-request

**Comment by sergiobelya** [comment]
@adrianmiu Thanks. But I just discovered my mistake in backward compatibility for php 5.3 (using short array syntax). Tomorrow I will fix it.

**Comment by sergiobelya** [comment]
Thanks. Waiting for next patch release.
