### ISSUE TITLE
Post back fields

### ISSUE THREAD

**Issue by tmblog** [siriusphp/validation#57]
Hello there, thanks for the brilliant library. I wanted to know if there is a built in way to post back passed values to the form if some fail validation e.g. in a form of 3 inputs 2 passed and 1 failed, when the user returns to the form after validation the passed fields are already filled in. Hope that makes sense. Cheers

**Comment by adrianmiu** [comment]
@tmblog Sorry but this is something that you have to implement in your application and it depends on how the data flows. Some applications redirects to the previous URL and store the form values in session. Others don't redirect and show the same form on the same request

**Comment by tmblog** [comment]
Thanks for the reply. The documentation seems to be down now and again. I am trying to figure out how to validate a pair of radion buttons e.g. one must be required then one of them has a dependents:

`cash-payment` or `card-payment` is required if card-payment is selected then:

```
'card-number:Card' => 'requiredWith(card-payment)',
'card-expiry:Expiry' => 'requiredWith(card-payment)',
'card-cvc:CVC' => 'requiredWith(card-payment)',
```

Can you help?
Thanks again.

**Comment by adrianmiu** [comment]
@tmblog Thanks for reporting the documentation issue. It's fixed now

Regarding your question, there are 2 ways to do it. One that works 100% is a hack

```php
if ($_POST['payment'] == 'card_payment') {
    $validator->add([
       'card-number:Card' => 'required'
   ]);
}
```

The other involves using the `requiredWhen` (ie: make a field required when some other conditions is met) and it is more complex than what I've used for testing so it might not work

```
$requiredWhenCardPaymentOptions = [
   'item' => 'payment',
   'rule' => 'equal',
   'rule_options' => ['value' => 'card-payment']
];
$validator->add('card-number:Card', 'requiredWhen', $requiredWhenCardPaymentOptions);
```

The shorter version should be
```php
$validator->add('card-number:Card', 'requiredWhen({"item":"payment","rule":"equal","rule_options":{"value":"card-payment"}})');
```

**Comment by tmblog** [comment]
This is perfect, they both work thank you! And thanks for sorting docs out.
