### ISSUE TITLE
RequiredWhen, RequiredWith and RequiredWithout try to trim the value, even if it is an integer.

### ISSUE THREAD

**Issue by TR3MIC** [siriusphp/validation#65]
I stumble across this error when using the `RequiredWithout` validation rule, but after looking into it, it appears to also be present in the `RequiredWhen` and `RequiredWith` rules.

Those rules will try to `trim` the value of the parameter to validate it, but the value can be an integer, where the `trim` function will throw an exception.

**Comment by adrianmiu** [comment]
Thanks for the PR
