### ISSUE TITLE
file upload and date

### ISSUE THREAD

**Issue by tmblog** [siriusphp/validation#70]
### Question

Hi I am using the latest version of this and trying to validate an uploaded file and date like so:

```
$validator->add(
		[
			'learner-name:Name' => 'required',
			'learner-license:License number' => 'required',
			'learner-email:Email' => 'required | email',
			'learner-mobile:Mobile' => 'required | minlength(11)',
			'learner-ted:Theory expiry date' => 'date',
			'learner-dlp:License Photo' => 'upload\required | upload\image',
			'course-id:Course not chosen' => 'integer'
		]
	);
```
The date field throws an error:
`Warning: date() expects at most 2 parameters, 3 given` any format I send gives that warning.
And the file upload never gets evaluated, am I missing something?

**Comment by adrianmiu** [comment]
For the files you should use 'uploadrequired | uploadimage'
For the date I don't see where in the code this function is executed with 3 parameters
